#! /bin/bash

# Simple script testing TCP connectivity to devices given in file, 
# one device per line and port given by parametr p. By default it test port 22.
# Script use timeout command/utility to do the test.
# Author: Jiri Kindl
# Version: 20200407

usage()
{
  cat << EOF
  Usage: $0 -r rulefile

  -r rulefile           file with comma seperated values: hostname,port (one record per line)
EOF
}

troubleshoot()
{
  echo '============================================================'
  echo " Source:            $source_host"	
  echo " Destination:       $1"
  echo " Destination Port:  $2"
  echo ""
  echo "TCP Trace results:"  
  traceroute -T -p $2 $1 
}

hosttest()
{
  #Using sed to remove windows eol and trim the Text (remove leading and trailing spaces)
  for TEST_HOST in $(sed -e 's/\r//' $RFILE | sed 's/^[ \t]*//' |sed 's/[ \t]*$//')
  do
    HOST=`echo $TEST_HOST | cut -d, -f1`
    PORT=`echo $TEST_HOST | cut -d, -f2`
    timeout $TIMEOUT_SECONDS bash -c "cat < /dev/null > /dev/tcp/${HOST}/${PORT}" &> /dev/null
    if [ "$?" -ne 0 ]; then
      echo "$source_host,$HOST,$PORT,Connection failed"
      if [ $TRBLSHT -eq 0 ]; then
        #echo "run troubleshooting"
	troubleshoot $HOST $PORT >> $TFILE
      fi  
    else
      echo "$source_host,$HOST,$PORT,Connection succeeded"
    fi
    sleep 1
  done
}

#main

RFILE=
TIMEOUT_SECONDS=5
PORT=22
TRBLSHT=1 #Troubleshoot = false

source_host=`hostname`


while getopts "r:t" OPTION
do
  case $OPTION in
  r)
    RFILE=$OPTARG
    ;;
  t)
    TRBLSHT=0
    ;;  
  esac
done


if [ -z $RFILE ]
then
  usage
  exit 1
fi

if [ $TRBLSHT -eq 0 ]; then
  RFILE_Base=`echo $RFILE| cut -d. -f1`
  TFILE="troubleshoot_$RFILE_Base.txt"
  echo "Run with troubleshooting ON"
  echo "troubleshooting file: $TFILE"
  echo "SOURCE INFO:" > $TFILE
  echo "------------" >> $TFILE
  echo -n "Source name: ">>$TFILE
  hostname >> $TFILE
  echo "Interfaces:">> $TFILE
  echo "-----------">> $TFILE
  ifconfig >> $TFILE
  echo "Routing:">> $TFILE
  echo "--------">> $TFILE
  netstat -rn >> $TFILE

fi

echo "Source,Destination,TCP Port,Result"
hosttest
exit 0
