#! /bin/bash

# Simple script testing ICMP connectivity to devices given in file, 
# one device per line. Script use ping command to do the test.
# Author: Jiri Kindl
# Version: 20200407

usage()
{
  cat << EOF
  Usage: $0 -h hostfile 

  -h hostfile		file with the list of host to test (one per line)
EOF
}

#test ICMP connectivity with ping
testICMP()
{
  return `ping -c 4 -q $1 | grep " 100% packet loss," | wc -l`
}

HFILE=

while getopts "h:" OPTION
do
  case $OPTION in
  h)
    HFILE=$OPTARG
    ;;
  esac
done

if [ -z $HFILE ] 
then
  usage
  exit 1
fi

#Using sed to remove windows eol and trim the Text (remove leading and trailing spaces)
for host in $(sed -e 's/\r//' $HFILE | sed 's/^[ \t]*//' |sed 's/[ \t]*$//')
do
  if `testICMP $host`
  then
    echo "$host,ok"
  else
    echo "$host,no connectivity"
  fi
done
